### ISSUE TITLE
CPU Frequence display error

### ISSUE THREAD

**Issue by airystar** [c2h2/aria-uboot#2]
On 800Mhz CPU:

c2h2: pinmux complete for Aria luna.
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿc2h2: setting CPU to 720MHz
c2h2: setting CPU to 720MHz, is completed.

**Comment by c2h2** [comment]
this is fixed.
